print("A day in the life of a colledge student:Mad Libs")
print("instructions: The program will prompt for a type of word to enter. After all words are entered the program will print a story")
timespan1 = input("Enter a time span: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter a verb ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a noun: ")
verb3 = input("Enter a verb endind in ing: ")
occupation1 = input("Enter a occupation: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
fp = input("Enter a famous person: ")
adj1 = input("Enter an adjective: ")
verb4 = input("Enter a verb: ")
noun6 = input("Enter a noun: ")
noun7 = input("Enter a plural noun: ")
adj2 = input("Enter an adjective: ")
noun8 = input("Enter a plural noun: ")
verb5 = input("Enter a verb: ")
prep = input("Enter a preposition: ")
verb6 = input("Enter a verb: ")
adj3 = input("Enter an djective: ")
noun9 = input("Enter a noun: ")
verb7 = input("Enter a verb: ")
adj4 = input("Enter an adjective: ")
print("\n\n")
print("Every %s, I wake up and get off my %s. I don`t always have time to %s a shower, but I always make sure to %s my hair. Once that`s done I get some %s, and then it`s off to my first %s. I often get caught %s in class. No one likes it when the %s gives a surprise %s. My second class is %s Theory. Dr. %s is incredibly %s, but I never %s her because of her thick %s. Her %s, however, are really %s. After lunch, I have no more %s and I`m free to %s %s my friends. Before I go to bed I %s a little bit. %s %s %s %s." % (timespan1, noun1, verb1, verb2, noun2, noun3, verb3, occupation1, noun4, noun5, fp, adj1, verb4, noun6, noun7, adj2, noun8, verb5, prep, verb6, adj3, noun9, verb7, adj4))
print("\n\n")