print("Driving test:Mad Libs")
print("instructions: The program will prompt for a type of word to enter. After all words are entered the program will print a story")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
adj3 = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
noun6 = input("Enter a noun: ")
noun7 = input("Enter a plural noun: ")
print("\n\n")
print("Driving a car can be fun if you follow this %s advice: When approaching a %s on the right, always blow your %s. Before making a %s turn, always stick your %s out of the window. Every 2000 miles, have your %s inspected and your %s checked. When approaching a school, watch out for %s %s. Above all, drive %s. The %s you save may be your own!" % (adj1, noun1, noun2, adj2, noun3, noun4, noun5, adj3, noun7, adverb, noun6))
print("\n\n")