print("Star Wars:Mad Libs")
print("instructions: The program will prompt for a type of word to enter. After all words are entered the program will print a story")
name1 = input("Enter a name: ")
adjective1 = input("Enter an adjective: ")
verb1 = input("Enter a verb: ")
sillyword1 = input("Enter a silly word: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter a plural noun: ")
verb2 = input("Enter a verb ending in ED: ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter a noun: ")
verb3 = input("Enter a verb ending in ED: ")
adjective2 = input("Enter an adjective: ")
print()
print()
print("Darth " + name1 + " looked at his master while his " + adjective1 + " breathing filled the room. He was told to go to " + verb1 + " evrything on the planet of " + sillyword1 + ". He got in his " + noun1 + " and jumped to hyperspace. Soon before he reached the planet, he dropped out of hyperspace and was attacked by Rebel " + noun2 + ". He " + verb2 + " them off and continued to the planet`s surface. He landed and confronted more opposition, slicing it down with his " + noun3 + ". He used the force to choke another Rebel, then " + noun4 + " him aside. He finished off all life on the planet with a/an " + adjective2 + " laugh.")
print("\n\n")