print("Video games:Mad Libs")
print("instructions: The program will prompt for a type of word to enter. After all words are entered the program will print a story")
adj1 = input("Enter an adjective: ")
name1 = input("Enter an Italian person's name: ")
occu1 = input("Enter an occupation: ")
verb1 = input("Enter a verb ending in ing: ")
plant1 = input("Enter a plural plant: ")
adj2 = input("Enter an adjective: ")
noun1 = input("Enter a plural noun: ")
noun2 = input("Enter a noun: ")
name2 = input("Enter a name of person in room: ")
print("\n\n")
print("%s %s Brothers is a popular video game where you control a/an %s as he/she runs through levels %s on enemies and eating %s to get %s and fireflowers so that he/she can throw %s at enemies. He does all this to save the %s from the evil %s." % (adj1, name1, occu1, verb1, plant1, adj2, noun1, noun2, name2))
print("\n\n")